# Copyright © 2024, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

allowRemediationCommits:
  individual: true
  thirdParty: false
require:
  members: false
