# Copyright © 2024, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

teams:
  - name: all
    role: Read
  - name: ospo-contributors
    role: Write
  - name: ospo-maintainers
    role: Maintain
