# PatchTransformer to set R_HOME and add to LD_LIBRARY_PATH environment variable in sas-launcher-job-config PodTemplate
#     value: /opt/sas/viya/home/sas-pyconfig/default_r/lib64/R
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: launcher-job-rpy2-transformer
patch: |-
  - op: add
    path: /template/spec/containers/0/env/-
    value:
      name: R_HOME
      value: /opt/sas/viya/home/sas-pyconfig/default_r/lib64/R #Change this to your R-HOME path.
target:
  kind: PodTemplate
  name: sas-launcher-job-config
---
# PatchTransformer to set R_HOME and add to LD_LIBRARY_PATH environment variable in sas-compute-job-config PodTemplate
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: compute-job-rpy2-transformer
patch: |-
  - op: add
    path: /template/spec/containers/0/env/-
    value:
      name: R_HOME
      value: /opt/sas/viya/home/sas-pyconfig/default_r/lib64/R #Change this to your R-HOME path.
target:
  kind: PodTemplate
  name: sas-compute-job-config
---
# PatchTransformer to set R_HOME and add to LD_LIBRARY_PATH environment variable in CASDeployment
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-rpy2-transformer
patch: |-
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/env/-
    value:
      name: R_HOME
      value: /opt/sas/viya/home/sas-pyconfig/default_r/lib64/R
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/env/-
    value:
      name: CASLLP_99_EDMR
      value: /opt/sas/viya/home/sas-pyconfig/default_r/lib64/R #Change this to your R-HOME path.
target:
  kind: CASDeployment
