apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-microanalytic-score-astores 
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi #change this to desired capacity
  storageClassName: sas #change this the desired storage class