apiVersion: builtin
kind: PatchTransformer
metadata:
  name: ingressclass-transformer
patch: |-
  - op: remove
    path: /spec/rules/1
  - op: replace
    path: /spec/tls
    value: [{hosts: [{{V4_CFG_INGRESS_FQDN}}], secretName: sas-ingress-certificate}]
target:
  kind: Ingress
  name: .*
  version: v1
vars:
- name: INGRESS_HOST
  objref:
    kind: ConfigMap
    name: ingress-input
    apiVersion: v1
  fieldref:
    fieldpath: data.INGRESS_HOST