# Copyright © 2024, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: builtin
kind: ConfigMapGenerator
metadata:
  name: sas-risk-cirrus-core-parameters
behavior: merge
literals:
  - SAS_LOG_LEVEL_RISKCIRRUSDEPLOYER=INFO
  - SAS_RISK_CIRRUS_DEPLOYER_RUN_SPECIFIC_INSTALL_STEPS=
  - SAS_RISK_CIRRUS_DEPLOYER_SKIP_SPECIFIC_INSTALL_STEPS=
  - SAS_UNSTRUCTURED_LOGGING=true
  - SAS_RISK_CIRRUS_SET_WORKFLOW_SERVICE_ACCOUNT_FLG=Y
  - SAS_RISK_CIRRUS_WORKFLOW_DEFAULT_SERVICE_ACCOUNT=sasadm
  # Internal-only environment variables
  - SAS_RISK_CIRRUS_DEPLOYER_INCLUDE_SAMPLES=Y
  - SAS_RISK_CIRRUS_CORE_IMPORT_FLG=Y
  - SAS_RISK_CIRRUS_SOLUTION_INPUT_DATA_DB_USER_NAME=
---
apiVersion: builtin
kind: SecretGenerator
metadata:
  name: sas-risk-cirrus-core-secret
behavior: merge
literals:
  - SAS_RISK_CIRRUS_SOLUTION_INPUT_DATA_DB_USER_SECRET=
