# Copyright © 2024, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cirrus-core-parameter-transform
patch: |-

  #Cirrus deployer environment variables
  - op: replace
    path: /data/SAS_LOG_LEVEL_RISKCIRRUSDEPLOYER
    value: "INFO"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_DEPLOYER_SKIP_SPECIFIC_INSTALL_STEPS
    value: ""

  - op: replace
    path: /data/SAS_RISK_CIRRUS_DEPLOYER_RUN_SPECIFIC_INSTALL_STEPS
    value: ""

  - op: replace
    path: /data/SAS_RISK_CIRRUS_SET_WORKFLOW_SERVICE_ACCOUNT_FLG
    value: "Y"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_WORKFLOW_DEFAULT_SERVICE_ACCOUNT
    value: "<<SAS_RISK_CIRRUS_WORKFLOW_DEFAULT_SERVICE_ACCOUNT>>"

  #Cirrus solution builder environment variables
  - op: replace
    path: /data/SAS_RISK_CIRRUS_SOLUTION_BUILDER_REPO_PREFIX
    value: "risk-cirrus-core"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_SOLUTION_BUILDER_REPO_PROTOCOL
    value: "https"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_SOLUTION_BUILDER_REPO_USER
    value: "<<SAS_RISK_CIRRUS_SOLUTION_BUILDER_REPO_USER>>"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_SOLUTION_GIT_REPO_FULL_URL
    value: "<<SAS_RISK_CIRRUS_REPO_FQDN>>/<<SAS_RISK_CIRRUS_REPO_USER>>/sas-risk-cirrus-core"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_SOLUTION_BUILDER_SOLUTION_BRANCH_PREFIX
    value: "NON-RND"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_SOLUTION_APPEND_NAMESPACE_TO_BRANCH_FLG
    value: "Y"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_SOLUTION_BUILDER_REPO_HOST
    value: "<<SAS_RISK_CIRRUS_REPO_HOST>>"

    #Cirrus code library environment variables
  - op: replace
    path: /data/SAS_RISK_CIRRUS_CODE_LIB_GIT_SETUP_NEEDED
    value: "Y"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_CODE_LIB_REPO_NAME
    value: "core-spre"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_CODE_LIB_REPO_USER
    value: "<<SAS_RISK_CIRRUS_REPO_USER>>"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_CODE_LIB_REPO_EMAIL
    value: "fsduser@mailhost.fyi.sas.com"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_CODE_LIB_GIT_REPO_FULL_URL
    value: "<<SAS_RISK_CIRRUS_REPO_FQDN>>/<<SAS_RISK_CIRRUS_REPO_USER>>/sas-risk-cirrus-core-spre"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_CODE_LIB_APPEND_NAMESPACE_TO_BRANCH_FLG
    value: "Y"

  - op: replace
    path: /data/SAS_RISK_CIRRUS_CODE_LIB_SKIP_PUSH_IF_BRANCH_EXISTS
    value: "N"

target:
  kind: ConfigMap
  name: sas-risk-cirrus-core-parameters*

---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cirrus-core-secret-transform
patch: |-

  #Cirrus solution builder secrets
  - op: replace
    path: /data/SAS_RISK_CIRRUS_SOLUTION_BUILDER_REPO_TOKEN
    value: "<<GITEA_CIRRUS_REPO_ACCESS_TOKEN_B64>>"

  #Cirrus code library secrets
  - op: replace
    path: /data/SAS_RISK_CIRRUS_CODE_LIB_REPO_TOKEN
    value: "<<GITEA_CIRRUS_REPO_ACCESS_TOKEN_B64>>"

target:
  kind: Secret
  name: sas-risk-cirrus-core-secret*
