name: Poll Managed App
description: Polls the status of a managed application with periodic Azure login.
inputs:
  mapp_rg_prefix:
    description: "Prefix for the resource group of the managed application"
    required: true
  mapp_suffix_id: 
    description: "Suffix ID for the managed application"
    required: true
  subscription_id:
    description: "Azure subscription ID"
    required: true
  pollInterval:
    description: "Maximum number of attempts to poll the managed application"
    required: false
    default: "30"
  maxDurationInSeconds:
    description: "Number of seconds to wait between each poll attempt"
    required: false
    default: "10000"
outputs:
  status:
    description: "Final status of the deployment"
    value: ${{ steps.poll.outputs.status }}
runs:
  using: "composite"
  steps:
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Poll loop
      id: poll
      run: |
        managed_rg="${{ inputs.mapp_rg_prefix }}-${{ inputs.mapp_suffix_id }}-mrg"
        
        bash "${{ github.action_path }}/poll.sh" \
          "${managed_rg}" \
          "${{ inputs.subscription_id }}" \
          "${{ inputs.pollInterval }}" \
          "${{ inputs.maxDurationInSeconds }}"
      shell: bash


