apiVersion: builtin
kind: PatchTransformer
metadata:
  name: launcher-job-r-transformer
patch: |-
  # Add r-config configMap
  - op: add
    path: /template/spec/containers/0/envFrom/-
    value:
      configMapRef:
        name: sas-open-source-config-r

target:
  kind: PodTemplate
  name: sas-launcher-job-config
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: compute-job-r-transformer
patch: |-
  # Add r-config configMap
  - op: add
    path: /template/spec/containers/0/envFrom/-
    value:
      configMapRef:
        name: sas-open-source-config-r

target:
  kind: PodTemplate
  name: sas-compute-job-config
  version: v1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: cas-r-transformer
patch: |-
  # Add R-config configMap
  - op: add
    path: /spec/controllerTemplate/spec/containers/0/envFrom/-
    value:
      configMapRef:
        name: sas-open-source-config-r

target:
  group: viya.sas.com
  kind: CASDeployment
  name: .*
  version: v1alpha1
---
apiVersion: builtin
kind: PatchTransformer
metadata:
  name: add-r-sas-java-policy-allow-list
patch: |-
  - op: add
    path: /data/SAS_JAVA_POLICY_ALLOW_DM_RHOME
    value: /opt/sas/viya/home/sas-pyconfig/default_r/lib64/R/bin/Rscript
target:
  kind: ConfigMap
  name: sas-programming-environment-java-policy-config
