apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sas-model-publish-git
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 30Gi #change this to desired capacity
  storageClassName: sas  # change this the desired storage class
