# Copyright © 2024, SAS Institute Inc., Cary, NC, USA.  All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

---
name: (RW) Download and Upload Package
run-name: download-and-upload-package-again

on:
  workflow_call:
    inputs:
      input_package_name:
        description: 'Package Name Input'
        required: true
        type: string
      output_package_name:
        description: 'Package Name Output'
        required: true
        type: string
      output_package_path:
        description: 'Path to the output package'
        required: true
        type: string
        
      
jobs:
  download-and-upload-package-again:
    name: Intermediate step to forward artifact
    runs-on: ubuntu-latest
    steps:
      - name: Download from call-retrieve-package
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.input_package_name }}

      - name: Upload again for call-upload-package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.output_package_name }}
          path: ${{ inputs.output_package_path }}